### ISSUE TITLE
Show brotli filesize

### ISSUE THREAD

**Issue by aomarks** [yousifalraheem/rollup-plugin-summary#11]
Would be nice to show filesize when compressed with brotli, like rollup-plugin-filesize can do: https://github.com/ritz078/rollup-plugin-filesize#showbrotlisize

**Comment by yousifalraheem** [comment]
@aomarks .. I've added support for brotli. Check version `1.2.x`

**Comment by aomarks** [comment]
Confirmed, thank you!
