### ISSUE TITLE
Incorrect sums in watch mode

### ISSUE THREAD

**Issue by aomarks** [yousifalraheem/rollup-plugin-summary#12]
**Describe the bug**
When rollup is run in `--watch` mode, `rollup-plugin-summary` shows incorrect sums, seemingly combining results across different builds. It is also a bit difficult to see the difference between each build, since they are combined into one giant table.

**To Reproduce**
Run a build with `rollup -c --watch`

**Expected behavior**
For each build, show the file sizes for that build, not including any sizes from previous builds.

**Screenshots**
In these 4 builds, the filesizes did not change, yet the total changes each time:

![image](https://user-images.githubusercontent.com/48894/94207544-a5d7bb00-fe7c-11ea-8e57-51c6e2fa42af.png)

**Desktop (please complete the following information):**
 - OS: macOS

P.S. Thanks for the plugin, nice enhancement over `rollup-plugin-filesize`.

**Comment by yousifalraheem** [comment]
@aomarks Sorry for this, I never tested it with watch mode. I fixed it, please test and let me know if the issue still persists.

**Comment by aomarks** [comment]
Confirmed, it's working perfectly now. Thanks again for the super quick fixes @yousifalraheem !
