### ISSUE TITLE
Option to disable minified

### ISSUE THREAD

**Issue by aomarks** [yousifalraheem/rollup-plugin-summary#29]
**Is your feature request related to a problem? Please describe.**
My Rollup build is already minified with Terser before hitting the summary step, so the Minified column is always the same as Size. Also, since the Minified column has to perform its own minification, the build is slowed down unnecessarily.

**Describe the solution you'd like**
Add a `showMinifiedSize` option that when set to `false` doesn't perform minification, and removes the Minified column.

**Describe alternatives you've considered**
N/A

**Additional context**
`rollup-plugin-filesize` has the `showMinifiedSize` option for this. Maybe we could have the same option here?

**Comment by yousifalraheem** [comment]
Alright, I'll look into it this weekend.
