### ISSUE TITLE
Rollup output with an array will lead to duplicated output of summary

### ISSUE THREAD

**Issue by KrabsWong** [yousifalraheem/rollup-plugin-summary#38]
**Describe the bug**

If I set an array in `rollup.config.js` such as the code snippet below, the second and third summary include the first and the second summary data.

Is there an option or way to avoid this case?

**To Reproduce**
```javascript
{
  // 入口文件我这里在components下统一导出所有自定义的组件
  input: './components/index.ts',
  output: [{
    file: 'dist/index.js',
    assetFileNames: '[name][extname]',
    format: 'umd',
    exports: 'named',
    name: 'test',,
    sourcemap: true,
  }, {
    dir: 'es',
    assetFileNames: '[name][extname]',
    format: 'es',
    sourcemap: true,
    preserveModules: true,
    
  }, {
    dir: 'lib',
    assetFileNames: '[name][extname]',
    format: 'cjs',
    exports: 'named',
    sourcemap: true,
    preserveModules: true,
  }],
  plugins: [
    summary()
  ],
}
```

**Expected behavior**

- an option for setting the different output seperately, such as each one has it's own summary

**Screenshots**
<img width="479" alt="image" src="https://user-images.githubusercontent.com/12368943/158300612-a059bf31-94a8-47e8-8fa1-14413e9476c9.png">

**Comment by yousifalraheem** [comment]
@KrabsWong Thank you for reporting this issue, I'll investigate and update you as soon as possible.
