### ISSUE TITLE
Reinstate suport for NodeJS 12

### ISSUE THREAD

**Issue by cstavaru** [yousifalraheem/rollup-plugin-summary#42]
Hello author,

AWS CodeBuild (a pretty popular platform for CICD stuff) does not support NodeJS > 12 on ARM platforms, so trying to use this RollupJS plugin breaks things since plugin version 1.4 because it requires NodeJS 14.x.

I would kindly ask you to consider supporting NodeJS 12.

Thanks !

**Comment by thigh** [comment]
Hi @cstavaru , by any chance are you getting an error complaining about requiring an es module from a commonjs file? I ask because we started getting this error shortly after updating dependencies and tracked it down to this plugin. Rolling the plugin back to 1.3 fixed the issue. We are also running in a node 12.x environment.

**Comment by srmxlt** [comment]
aaargh! spent a few hours wondering what happened ... in any case, rolling back to 1.3 fixed it. thanks for the post and great tool!

**Comment by yousifalraheem** [comment]
@cstavaru 
I'm working on a [refactoring](https://github.com/yousifalraheem/rollup-plugin-summary/pull/44) that should smooth things further. I will look into node 12 support after I merge the changes.

**Comment by TownCube** [comment]
I'm on Node v14.19.0 and I'm getting the error mentioned above. Tracked it down to this plugin as well.

> [!] Error: While loading the Rollup configuration from "rollup.config.js", Node tried to require an ES module from a CommonJS file, which is not supported. A common cause is if there is a package.json file with "type": "module" in the same folder. You can try to fix this by changing the extension of your configuration file to ".cjs" or ".mjs" depending on the content, which will prevent Rollup from trying to preprocess the file but rather hand it to Node directly.

**Comment by yousifalraheem** [comment]
@TownCube .. Are you still experiencing the same issue with node v14+?

In the [2.0.0](https://github.com/yousifalraheem/rollup-plugin-summary/releases/tag/v2.0.0) release I have switched to building it for both `es` and `cjs`.

**Comment by yousifalraheem** [comment]
@cstavaru .. Support for node 12 proved to be challenging and it isn't worth the effort since it is no longer maintained. I highly recommend that you upgrade to a higher version that is receiving at least security updates.
