### ISSUE TITLE
Doesn't work with rollup 2.75.6

### ISSUE THREAD

**Issue by soetji** [yousifalraheem/rollup-plugin-summary#60]
**Describe the bug**
Getting the following error:
[!] Error: While loading the Rollup configuration from "rollup.config.js", Node tried to require an ES module from a CommonJS file, which is not supported.

**Comment by yousifalraheem** [comment]
@soetji  .. thank you for submitting this bug. I'll investigate

**Comment by soetji** [comment]
The above error message I got when I use rollup-plugin-summary 2.0 with rollup 2.75.6. It works with rollup 3.3.0.

**Comment by ouweiya** [comment]
At first I only installed Rollup globally, later I added Rollup to local dependencies and finally fixed the issue.
My environment:
"rollup": "^3.3.0",
"rollup-plugin-summary": "^2.0.0"
Node v16.14.2

**Comment by yousifalraheem** [comment]
I think we can safely close this ticket since the solution is just to use a newer version of `rollup` or use an old version of `rollup-plugin-summary`
