### ISSUE TITLE
Rollup 4.x

### ISSUE THREAD

**Issue by NGPixel** [yousifalraheem/rollup-plugin-summary#64]
**Describe the bug**
`rollup-plugin-summary` doesn't have `rollup >= 4.0.0` as a valid peer dependency, preventing the use of the latest rollup release.

**To Reproduce**

1. Install latest `rollup@4.0.2`
2. Attempt to install `rollup-plugin-summary`

```
 WARN  Issues with peer dependencies found
.
└─┬ rollup-plugin-summary 2.0.0
  └── ✕ unmet peer rollup@^2.68.0||^3.0.0: found 4.0.2
```

**Expected behavior**

Being able to use `rollup-plugin-summary` with the latest rollup

**Comment by tsteinke-iabbb** [comment]
@yousifalraheem Thanks for making this update!

It looks like the GitHub action that was meant to create the NPM release for this update failed. Are you able to get a new NPM release out for this?

**Comment by domyn** [comment]
@yousifalraheem bump
