### ISSUE TITLE
You forgot to publish latest version to NPM

### ISSUE THREAD

**Issue by mrbinky3000** [yousifalraheem/rollup-plugin-summary#67]
**Describe the bug**
You recently updated the peer dependencies to include rollup version 4.  However, you did not publish your changes to npm.

**To Reproduce**
Install rollup v4.  Install rollup-plugin-summary and npm will complain that rollup-plugin-summary has a conflict with rollup 4.

**Expected behavior**
It should install without npm issues

**Screenshots**

<img width="789" alt="Screenshot 2023-12-01 at 9 42 05 AM" src="https://github.com/yousifalraheem/rollup-plugin-summary/assets/161068/2a437d89-15bc-4c78-bf91-971653ca8ad3">

**Comment by SanderBreivik** [comment]
@yousifalraheem Do you have time to publish latest version to NPM?

**Comment by yavorski** [comment]
It looks like `semantic-release` is not creating/publishing new version.
Maybe commit with specific message is required or a new tag in the repository.

From last log:
[semantic-release › ℹ  There are no relevant changes, so no new version is released.](https://github.com/yousifalraheem/rollup-plugin-summary/actions/runs/7918388729/job/21616682125#step:7:124)

**Comment by jitendraP-ashutec** [comment]
@yavorski any news for release updated version ?

**Comment by stavarengo** [comment]
+1 :)

**Comment by arielsalminen** [comment]
Facing the same issue as well. Wondering if there’s any update on this? To overcome this issue for now, I’ve added this to the package.json:

```
"overrides": {
    "rollup-plugin-summary": {
      "rollup": "4.13.0"
    }
}
```

Seems to work fine, but obviously a little annoying to have to have this override defined.

**Comment by yousifalraheem** [comment]
Sorry for the late response. I apologize for not giving as much support as I should have. If you would like to see changes happening to this package quickly, feel free to submit a PR. I'll look into this and publish a new version soon that is compatible with rollup v4
